### PR TITLE
Adding rat report to After Failure procedure

### PR DESCRIPTION
**Pull request by ebenezergraham**

### CODE REVIEW

**Comment by aasaru** [comment]
Why you want to call 
  - ./gradlew rat
in .travis.yml

Gradle task "rat" is already called by travis.sh when building pull requests.

**Comment by ebenezergraham** [comment]
> Why you want to call
> 
> * ./gradlew rat
>   in .travis.yml
> 
> Gradle task "rat" is already called by travis.sh when building pull requests.

I wasn't able to access the build after the script stage and so I have to rerun the rat check to be able to output the report

**Comment by aasaru** [comment]
I now checked the documentation and indeed - travis does not preserve state between stages. So yes, your solution is correct.

**Comment by aasaru** [comment]
I also found that newest version (0.4.0) of rat plugin outputs failing licenses list 
[Documentation](https://github.com/eskatos/creadur-rat-gradle/releases) states:
rat task failure now reports the missing licenses in the task exception message

The problem is that the new version of plugin would require updating Gradle version as it needs Gradle 4.7 or Gradle 5.x. (current version used by fineract-cn-* is 3.4.1).

**Comment by ebenezergraham** [comment]
> I also found that newest version (0.4.0) of rat plugin outputs failing licenses list
> [Documentation](https://github.com/eskatos/creadur-rat-gradle/releases) states:
> rat task failure now reports the missing licenses in the task exception message
> 
> The problem is that the new version of plugin would require updating Gradle version as it needs Gradle 4.7 or Gradle 5.x. (current version used by fineract-cn-* is 3.4.1).

Using 0.4.0 will make the code cleaner and eliminate the after_failure script. We can discuss upgrading the Gradle version with the community and run tests to assert it is safe to move to the latest. So that we can upgrade rat to 0.4.0 when it's officially released.

**Comment by ebenezergraham** [comment]
I have upgraded my gradle versions to 5.4.1. It seems to upgrade to 5.x may not be straight forward. This might cause a ripple effect which will require other spring dependencies to be upgraded.

For now, I suggest that we merge these additions and upgrade to apache rat 0.4.0 when the community moves to gradle to 4.x +

**Comment by ebenezergraham** [comment]
> I now checked the documentation and indeed - travis does not preserve state between stages. So yes, your solution is correct.

**Comment by aasaru** [comment]
Yeah, upgrading to Gradle 5+ is not an easy task as there are a lot of changes.
I agree with the plan.

**Comment by ebenezergraham** [comment]
Hi @awasum, in light of this, can you help merge the PRs for FINCN-157 branches (Adding rat report to After Failure procedure) across all of the fineract-cn-* repositories?

**Pull request merged**
